#!/usr/bin/env python3
"""Drift gate for docs/plans/INDEX.md.

docs/plans/INDEX.md is hand-maintained (a date/slug/status/area table), not
generated by gen_doc_index.py, so it silently drifts when a plan is added and
the row is forgotten. This check enforces a 1:1 mapping between the live
working set (the `*.md` files in docs/plans/, excluding INDEX.md) and the rows
of the index table:

  * every live plan file has exactly one row,
  * every row links to a live plan file (not a missing or already-archived one).

Finished plans live in docs/plans/archive/ and are intentionally NOT listed
here, so an archived file having no row is correct — the failure modes are a
live file with no row, or a row pointing at a file that is gone.

Usage:
    python3 scripts/docs/check_plans_index.py          # nonzero on drift (CI gate)
    python3 scripts/docs/check_plans_index.py --list    # print the parsed mapping

Pairs with `archive_plans.py --check` (which keeps finished plans OUT of the
working set) to fully pin docs/plans/.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

PLANS_DIR = Path("docs/plans")
INDEX = PLANS_DIR / "INDEX.md"

# A table row links the plan as `| [text](link.md) | ... |`. We take the link
# target (second capture) as the authoritative filename.
_ROW = re.compile(r"^\|\s*\[[^\]]+\]\(([^)]+\.md)\)\s*\|")


def _index_rows(text: str) -> list[str]:
    out: list[str] = []
    for line in text.splitlines():
        m = _ROW.match(line)
        if m:
            out.append(m.group(1))
    return out


def main(argv: list[str]) -> int:
    if not INDEX.exists():
        print(f"check_plans_index: missing {INDEX}", file=sys.stderr)
        return 1

    live = {
        p.name
        for p in PLANS_DIR.glob("*.md")
        if p.name != "INDEX.md"
    }
    rows = _index_rows(INDEX.read_text(encoding="utf-8"))

    if "--list" in argv:
        for r in sorted(rows):
            print(("ok   " if r in live else "GONE ") + r)
        return 0

    seen: dict[str, int] = {}
    for r in rows:
        seen[r] = seen.get(r, 0) + 1

    missing_row = sorted(live - set(rows))          # live file, no row
    dangling = sorted(set(rows) - live)             # row, no live file
    duplicates = sorted(r for r, n in seen.items() if n > 1)

    problems = False
    if missing_row:
        problems = True
        print("check_plans_index: live plans missing from INDEX.md:", file=sys.stderr)
        for r in missing_row:
            print(f"  + {r}", file=sys.stderr)
    if dangling:
        problems = True
        print(
            "check_plans_index: INDEX.md rows point at non-live files "
            "(archived or deleted — remove the row):",
            file=sys.stderr,
        )
        for r in dangling:
            print(f"  - {r}", file=sys.stderr)
    if duplicates:
        problems = True
        print("check_plans_index: duplicate rows in INDEX.md:", file=sys.stderr)
        for r in duplicates:
            print(f"  ! {r}", file=sys.stderr)

    if problems:
        print(
            "\ncheck_plans_index: FAIL — edit docs/plans/INDEX.md so its table "
            "matches the live working set.",
            file=sys.stderr,
        )
        return 1

    print(f"check_plans_index: OK — {len(live)} live plans, all indexed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
