#!/usr/bin/env python3
"""Generate (or verify) an INDEX.md for a docs directory.

Token-efficiency tooling: lets a fresh agent landing in a docs subdirectory read
one ~screen-sized map (title + one-line summary per file) instead of opening
every file to find what's relevant.

For each `*.md` in the directory (excluding INDEX.md / README.md) it extracts:
  - title:   the first `# H1`, else a `title:` frontmatter field, else the slug
  - summary: a `summary:` / `tldr:` frontmatter field, else the first prose line
              (or the `> ` blockquote TL;DR a doc may put under its H1)

Usage:
    python3 scripts/docs/gen_doc_index.py docs/solutions docs/adr ...
    python3 scripts/docs/gen_doc_index.py --check docs/solutions   # CI: nonzero if stale

The same (dir, sorted files, titles, summaries) inputs always produce identical
output, so `--check` is a clean drift gate.
"""
from __future__ import annotations

import sys
from pathlib import Path

MARKER = "<!-- GENERATED by scripts/docs/gen_doc_index.py — do not edit by hand. -->"


def _frontmatter(text: str) -> dict[str, str]:
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    fm: dict[str, str] = {}
    for line in text[3:end].splitlines():
        if ":" in line and not line.lstrip().startswith("#"):
            key, _, val = line.partition(":")
            fm[key.strip().lower()] = val.strip().strip("'\"")
    return fm


def _body_after_frontmatter(text: str) -> str:
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            return text[end + 4 :]
    return text


def extract(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    fm = _frontmatter(text)
    body = _body_after_frontmatter(text)

    title = ""
    summary = fm.get("summary") or fm.get("tldr") or ""

    for raw in body.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("# ") and not title:
            title = line[2:].strip()
            continue
        if line.startswith("#"):
            continue
        if not summary and not line.startswith(("<!--", "|", "---", "```")):
            # First real prose line (strip a leading blockquote marker).
            summary = line.lstrip("> ").strip()
            if title:
                break
    if not title:
        title = fm.get("title") or path.stem
    summary = " ".join(summary.split())
    if len(summary) > 160:
        summary = summary[:157].rstrip() + "…"
    return title, summary


def render(directory: Path, recursive: bool = False) -> str:
    globber = directory.rglob if recursive else directory.glob
    files = sorted(
        (p for p in globber("*.md") if p.name not in {"INDEX.md", "README.md"}),
        key=lambda p: p.relative_to(directory).as_posix(),
    )
    rel = directory.as_posix()
    lines = [
        MARKER,
        f"# {rel} — index",
        "",
        f"{len(files)} documents. Auto-generated map — read this to find the "
        "relevant file, then open only that one.",
        "",
        "| Document | Summary |",
        "|---|---|",
    ]
    for p in files:
        link = p.relative_to(directory).as_posix()
        title, summary = extract(p)
        title = title.replace("|", "\\|")
        summary = (summary or "—").replace("|", "\\|")
        lines.append(f"| [{title}]({link}) | {summary} |")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    check = "--check" in argv
    recursive = "--recursive" in argv
    dirs = [Path(a) for a in argv if not a.startswith("--")]
    if not dirs:
        print(
            "usage: gen_doc_index.py [--check] [--recursive] <dir> [<dir> ...]",
            file=sys.stderr,
        )
        return 2

    stale: list[str] = []
    for directory in dirs:
        if not directory.is_dir():
            print(f"skip (not a dir): {directory}", file=sys.stderr)
            continue
        content = render(directory, recursive=recursive)
        index = directory / "INDEX.md"
        existing = index.read_text(encoding="utf-8") if index.exists() else ""
        if check:
            if existing.rstrip() != content.rstrip():
                stale.append(str(index))
        else:
            index.write_text(content, encoding="utf-8")
            print(f"wrote {index}")

    if check and stale:
        print("Stale INDEX.md (run gen_doc_index.py to regenerate):", file=sys.stderr)
        for s in stale:
            print(f"  {s}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
