"""Block harness — render ONE candidate block on neutral tokens for judging.

A tournament needs to see each candidate block in isolation: not embedded in a full
page (where a strong hero could halo a weak gallery), but alone on a neutral canvas
that uses the real design system so the judge scores the block's own craft. This
module builds that one-block ``index.astro``; the live wrapper drops it into a copy
of the ``astro-premium`` scaffold, builds, and shoots it.

Pure + deterministic: the index.astro generation and the per-slot sample data are
plain functions, so the contract is unit-tested without npm or Chromium.
"""

from __future__ import annotations

from packages.web.block_tournament import BlockCandidate

# Representative content per slot so a candidate renders with real-looking data. No
# images (the harness judges layout/type/craft, not photography) — kept deliberately
# generic so the score reflects the block, not the copy.
_SAMPLE_DATA: dict[str, dict] = {
    "hero": {
        "eyebrow": "Local Craft",
        "headline": "Work you can point to.",
        "subhead": "A studio that treats your project like its portfolio piece.",
        "primaryCta": "Get a quote",
        "secondaryCta": "See the work",
        "image": None,
        "imageAlt": "Hero",
    },
    "split": {
        "index": "01",
        "heading": "Built around the proof.",
        "body": "Every claim on the page is sourced from real evidence.",
        "points": ["20 years in business", "Careful, documented cleanup", "Fixed, clear pricing"],
    },
    "bento": {
        "heading": "The work, up close",
        "items": [
            {"title": "Detail 1", "body": "Documented cleanup on every job.", "span": "wide"},
            {"title": "Detail 2", "body": "Two decades of local work.", "span": "tall"},
            {"title": "Detail 3", "body": "Clear pricing up front."},
        ],
    },
    "process": {
        "heading": "How it goes",
        "steps": [
            {"title": "Reach out", "body": "Tell us what you need."},
            {"title": "We scope it", "body": "A clear plan and a clear price."},
            {"title": "It gets done", "body": "Careful work, done right."},
        ],
    },
    "fullbleed": {
        "image": None,
        "alt": "Band",
        "kicker": "",
        "headline": "Done right, the first time.",
        "cta": "Get a quote",
    },
    "cta": {
        "headline": "Ready when you are.",
        "subhead": "Tell us about your project and we'll send a clear quote.",
        "cta": "Get a quote",
    },
}

_FONTS_LINK = (
    "https://fonts.googleapis.com/css2?"
    "family=Fraunces:opsz,wght@9..144,400..600"
    "&family=Cormorant+Garamond:wght@500;600"
    "&family=Inter:wght@400;500;600&family=Inter+Tight:wght@500;600"
    "&family=Newsreader:opsz@6..72&family=Spline+Sans+Mono:wght@400;500&display=swap"
)


def sample_data_for(slot: str) -> dict:
    """Representative ``data`` for a slot (the shape the block must accept)."""

    return _SAMPLE_DATA.get(slot, {})


def harness_index_astro(candidate: BlockCandidate) -> str:
    """An index.astro that renders just this candidate block on a neutral canvas."""

    import json

    data = json.dumps(sample_data_for(candidate.slot))
    return f"""---
// Block harness — renders a single candidate block for the tournament judge.
// Generated by packages/web/block_harness.py. Do not edit by hand.
import "../styles/global.css";
import {candidate.component} from "{candidate.component_path}";
---
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Block harness — {candidate.component}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link rel="stylesheet" href="{_FONTS_LINK}" />
</head>
<body class="grain">
  <main id="main">
    <{candidate.component} data={{{data}}} />
  </main>
</body>
</html>
"""
